manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-config-charybdis
      url: https://github.com/iamtienng/zmk-config-charybdis
      revision: main
      path: modules/zmk-config-charybdis
    - name: doodoo
      url: https://github.com/ggguhfyj/zmk-config-charybdis.git
      revision: main
      path: modules/doodoo
    - name: zmk-for-charybdis
      url: https://github.com/Vzhao-L/zmk-for-charybdis.git
      revision: main
      path: modules/zmk-for-charybdis
    - name: zmk-keyboards-charybdis
      url: https://github.com/victorlucachi/zmk-keyboards-charybdis
      revision: main
      path: modules/zmk-keyboards-charybdis
  self:
    path: config
